### ISSUE TITLE
Problems with initializeReasoner(Object kbase, String modelName, String rules, ...)

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#808] opened 2021-10-07 17:30 UTC
JenaReasonerPlugin's initializeReasoner(Object kbase, String modelName, String rules, List<ConfigurationItem> preferences) does not work properly when the in-memory OntModel passed in SADL models that have rules. The extension JenaAugmentedReasonerPlug has the same problem plus the additional problem that any rules passed into this initializeReasoner will not be handled properly with staged rules.

**Comment by crapo** [comment] 2021-10-07 18:40
@agabaldon , I have implemented the 3rd option from our emails. Method initializeReasoner(Object kbase, ...), where kbase is an OntModel, will stash both a preloaded model and any preloaded rules (which must be stage 0). So the normal process should be followed. Just call initializeReasoner(yourOntModel, ...) and then use the reasoner. You should not have to worry about any loading of imports or rules, should happen only when needed. Please let me know of any  issues.
Pushed to branch GH-808.

**Comment by crapo** [comment] 2021-10-09 00:16
@agabaldon , I have fixed JenaAugmentedReasonerPlug.getInferredModel(true) to return aggregated deductions. Pushed to branch GH-808. In order to get deductions with staged rules, the configuration for derivations must be enabled. You can pass that configuration setting into JenaAugmentedReasonerPlugin.initializeReasoner(bject kbase, String modelName, String rules, List<ConfigurationItem> preferences) as the last argument. The way to setup the necessary preference to pass in is as follows:

"""
import com.ge.research.sadl.reasoner.ConfigurationItem;
...
List<ConfigurationItem> preferences = new ArrayList<ConfigurationItem>();
String[] catHier = new String[1];
catHier[0] = reasoner.getReasonerFamily(); 
ConfigurationItem ci = new ConfigurationItem(catHier);
ci.addNameValuePair(ci.new NameValuePair("pDerivationLogging", "Deep"));  // could also be "Shallow"
preferences.add(ci);
"""

Pass preferences as last argument.

**Comment by crapo** [comment] 2021-10-09 00:36
I also added documentation of how to do this to the Default Values and Staged Rules documentation.

**Comment by agabaldon** [comment] 2021-10-29 20:17
I finally got to try these changes and I'm getting an error caused by the repoType not getting set before invoking getInferredModel. I guess that initializeReasoner should set repoType (the version  initializeReasoner(String folderName, String _modelName, List<ConfigurationItem> _preferences, String _repoType) of initializeReasoner sets repoType, but initializeReasoner(Object kbase, String modelName, String rules, List<ConfigurationItem> preferences) does not), but I'm not sure.

After calling initializeReasoner, I call getInferredModel and when the execution gets to getReasonerOnlyWhenNeeded there it throws an exception when it tries to validateFormat(repoType) and repoType is null.

com.ge.research.sadl.reasoner.ConfigurationException: Format 'null' is not supported by reasoner 'Augmented-Jena'.
	at com.naturalsemanticsllc.sadl.reasoner.JenaAugmentedReasonerPlugin.getReasonerOnlyWhenNeeded(JenaAugmentedReasonerPlugin.java:146)
	at com.naturalsemanticsllc.sadl.reasoner.JenaAugmentedReasonerPlugin.prepareInfModel(JenaAugmentedReasonerPlugin.java:304)
	at com.naturalsemanticsllc.sadl.reasoner.JenaAugmentedReasonerPlugin.getInferredModel(JenaAugmentedReasonerPlugin.java:216)

**Comment by crapo** [comment] 2021-10-29 21:38
@agabaldon , initializeReasoner(Object kbase, ...) gets a format from the ConfigurationManager's ISadlJenaModelGetter. If repoType is null it is set to this format, so I guess if the ISadlJenaModelGetter has a null format then repoType will be null. I don't think this happens in SADL. IReasoner method initializeReasoner(Object kbase, ....) could certainly have a repoType argument. Do you want me to make that change?

**Comment by agabaldon** [comment] 2021-10-29 22:19
Oh, I'm in a branch that merges GH-794 and GH-808 and in GH-794 the code where you get the format from the ConfigurationManager is commented out. I don't know what it is commented out, but I add it back and try that.

**Comment by agabaldon** [comment] 2021-10-29 23:52
Ok, so that block of code is commented out because it is incompatible with the new GetterPutter interface.

**Comment by crapo** [comment] 2021-11-01 12:41
@agabaldon , I've kind of lost track. Neither the branch for #794 nor the branch for #810 have been merged with development I think. Isn't this as simple as adding repoType as an argument to initializeReasoner(Object kbase, ...)? I can do that if you like.

**Comment by agabaldon** [comment] 2021-11-01 17:56
#810 has been merged. #808 and #794 haven't. I'll merge #794 into #808 and push it. The block of code that was commented out (on branch #794) used to get the repoType from the ConfigurationManager. I think the question now is: should a compatible version of that block of code be added back to initializeReasoner(Object kbase, ...)?

**Comment by crapo** [comment] 2021-11-01 18:14
No, I think not. I think it would be better to pass repoType as an added argument to the method, as I stated above.

**Comment by agabaldon** [comment] 2021-11-01 19:01
I added the argument and pushed the change to GH-808. Also fixed a bug where stage0Rules were not being loaded in getReasonerOnlyWhenNeeded()

**Comment by agabaldon** [comment] 2021-11-01 19:08
Well, I shouldn't have done that. There are now errors in OwlToSadl and JenaBasedSadlInferenceProcessor. Not sure how to get the repoType before the calls to initializeReasoner are made there.

**Comment by agabaldon** [comment] 2021-11-01 20:11
Ok, I fixed the errors and now it builds. But there are test errors, not sure if caused by these changes or earlier ones.

**Comment by crapo** [comment] 2021-11-02 12:26
@agabaldon , I'm about to take a look. Checking out GH-808 will give me the latest of everything, right?

**Comment by crapo** [comment] 2021-11-02 12:32
@agabaldon , I see more than test failures. Looks like incompatibilities in code from merging.

**Comment by crapo** [comment] 2021-11-02 13:16
@agabaldon , it looks to me like the issue in the failing test OwlToSadlTest.test06 is that we've removed the default repoType. But it doesn't seem that we should really need one as we already have the loaded OntModel that we're trying to translate to SADL. I'm going to pursue this line of thinking....

**Comment by agabaldon** [comment] 2021-11-02 14:10
Great! Yes, GH-808 has the latest.

**Comment by crapo** [comment] 2021-11-02 14:21
@agabaldon , just pushed a small fix, all tests now pass. Not entirely sure this is the best way ultimately--providing a default format. but it is very simple and solves the immediate problem. However its done, this test case has no associated project with other imported OWL models, so the format is really not representative of anything. The real test will be in actual projects that have a repoType. In these cases the ConfigurationManager should have a repoType, which will be passed in.

**Comment by crapo** [comment] 2021-12-08 15:46
@agabaldon , is this issue resolved? If so, can we close it?

**Comment by agabaldon** [comment] 2022-01-11 18:25
I think this is resolved, but the GH-808 branch has not been merged into development. We need to make sure the merge doesn't break things.

**Closed as completed** 2022-02-02 22:07 UTC
