### ISSUE TITLE
Import of http://com.ge.research.sadl/sadlserver/Services in ServicesConfig.sadl shows error

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#572] opened 2020-11-19 21:43 UTC
Created a ServicesConfig.sadl file which resulted in the generation of a SadlServicesConfigurationConcepts.owl file in OwlModels. Then adding
 import "http://com.ge.research.sadl/sadlserver/Services".
to ServicesConfig.sadl shows error
  Couldn't resolve reference to SadlModel 'http://com.ge.research.sadl/sadlserver/Services'.

**Comment by crapo** [comment] 2020-11-20 12:30
Just realized this is duplicate of #550. It is also related to #549 .

**Comment by crapo** [comment] 2020-11-30 22:23
@agabaldon , I think that this issue can be closed with the merging of PR #573 . Do you agree?

**Comment by agabaldon** [comment] 2020-12-03 21:30
This and #549 ?

**Comment by crapo** [comment] 2020-12-03 22:22
yes, I believe so

**Comment by crapo** [comment] 2020-12-04 22:12
With all outstanding PRs merged, I believe this is resolved.

**Closed as completed by crapo** 2020-12-04 22:12 UTC
