### ISSUE TITLE
Mappings when one project depends upon another

### ISSUE THREAD

**Issue by GEGlobalResearch** [SemanticApplicationDesignLanguage/sadl#523] opened 2020-09-21 19:51 UTC
When one project depends upon another, the OwlModels/ont-policy.rdf mapping file does not contain the mappings necessary to handle imports correctly. It currently works (at least in some cases) because Jena caches models and provides them. But other things that depend on correct dependencies (e.g., import graph) will not be correct.

**Comment by crapo** [comment] 2020-10-05 16:23
@kittaakos , to fix this error I would need to get the inter-project dependencies in the SADL backend, com.ge.research.sadl.jena, either in JenaBasedSadlInferenceProcessor, or get it in the JenaBasedSadlModelProcessor and store it for inference. Is this possible?

**Comment by kittaakos** [comment] 2020-10-06 06:37
> Is this possible?

Sure, it is possible. We can come up with a solution but such an out of the box project dependency thing does not exist in Xtext (`xtext-core`).

**Comment by crapo** [comment] 2020-10-06 12:08
I'm thinking that if we can simply detect the project dependency we can put it into the configuration.rdf file and then inference as well as possibly SadlServer (eclipse, web independent) can use the information as needed.

**Comment by crapo** [comment] 2020-10-06 20:21
@kittaakos , setting up meeting to discuss this. It this time doesn't work please suggest a time.

**Comment by crapo** [comment] 2020-10-14 14:33
@agabaldon , @weisenje , I'd like to move the conversation around this to this github issue. I'm going to put some of my notes here and invite you to comment, collaborate as we work out a solution. 
The capability to handle imports from a referenced project is needed for Inference, Graphing, anything that doesn’t use Xtext linking to handle imports. Possible approaches include: 
a) Just add mapping of an import from another project to the ont-policy.rdf file. This won’t really work—the imported file might in turn import another file in the depended-on project, and that wouldn’t be in the mapping file.
b) Record the project dependency and when there is an import not resolved in the current project check for referenced projects and access the referenced projects' ConfigurationManager and let it do all the work. Where should this be recorded?
b1) Will this dependency, as this KB depends on that KB, be supported in SadlServer? If it’s implemented correctly using dependencies in ConfigurationManager support in SadlServer should be free, as long as all projects involved are under kbaseRoot.
b2) Probably should be stored in configuration.rdf.
b3) How is a project identified in configuration.rdf?
b3a) Last segment in the dependency URI?
b3b) Then just search projects under kbaseRoot for a project with that name.
b3c) This would require that project names be unique—I think this is already necessary in SadlServer implementation.
c) Can a project depend on a second project which depends on a third project?
c1) If properly implemented, recursion will work so the dependency chain can be arbitrarily deep. For this to work, the request for an actualURL should call a ConfigurationManager for the depended-on project, which, if not found, can look, for a depended-on project in turn. This looks like it would most simply be a depth-first search as each called ConfigurationManager would exhaust its dependencies before returning failure.

**Comment by crapo** [comment] 2020-10-15 18:40
@kittaakos , when I try to build on this branch I get this error:
`[ERROR] Failures:
[ERROR]   SadlRenameTest.testRenameConflict:254->testRename:359 Expceted a failure with message: 'Refactoring cannot be performed'.
[ERROR]   SadlRenameTest.testRenameDecl_MultiFile:229->testRename:382->assertEquals:259->AbstractLanguageServerTest.assertEquals:1398 expected:<changes :
[    Other.sadl : Bar [[2, 11] .. [2, 14]]
    TestMe.sadl : Bar [[1, 0] .. [1, 3]]
`
The error appears to be in the language server:
`				languageServer.rename(new RenameParams => [
					textDocument = new TextDocumentIdentifier(uri)
					position = new Position(line, column)
					it.newName = configuration.newName
				]).get
				fail('''Expceted a failure with message: '«configuration.error»'.''')
`.
Was this expected?

**Comment by kittaakos** [comment] 2020-10-19 09:32
> on this branch

I am not sure which branch did you try, but if you are referring to the [`GH-523--project-dep`](https://github.com/SemanticApplicationDesignLanguage/sadl/tree/GH-523--project-dep) for https://github.com/SemanticApplicationDesignLanguage/sadl/pull/531, then it works for me if I omit (`git reset --hard HEAD~2`) your changes.

See the steps:
```
% java --version \
&& rm -rf sadl-tmp \
&& mkdir sadl-tmp \
&& cd sadl-tmp \
&& git clone https://github.com/SemanticApplicationDesignLanguage/sadl.git \
&& cd sadl \
&& git checkout origin/GH-523--project-dep -b GH-523--project-dep \
&& git reset --hard HEAD~2 \
&& git rev-parse --short HEAD \
&& cd sadl3/com.ge.research.sadl.parent \
&& mvn clean \
&& mvn verify -U
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
Cloning into 'sadl'...
remote: Enumerating objects: 491, done.
remote: Counting objects: 100% (491/491), done.
remote: Compressing objects: 100% (241/241), done.
remote: Total 59171 (delta 166), reused 368 (delta 105), pack-reused 58680
Receiving objects: 100% (59171/59171), 87.62 MiB | 4.86 MiB/s, done.
Resolving deltas: 100% (28710/28710), done.
Checking out files: 100% (3540/3540), done.
Branch 'GH-523--project-dep' set up to track remote branch 'GH-523--project-dep' from 'origin'.
Switched to a new branch 'GH-523--project-dep'
HEAD is now at bddf2426 GH-523: Initial API for the project dependencies support.
bddf2426
[INFO] Scanning for projects...
```

Output:
```
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: com.ge.research.sadl:com.ge.research.sadl.xtextgenerator:3.4.1-SNAPSHOT @ /Users/akos.kitta/Desktop/xxx/sadl-tmp/sadl/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.xtextgenerator/pom.xml
[INFO] Fetching p2.index from https://download.eclipse.org/releases/2020-03/
[INFO] Adding repository https://download.eclipse.org/releases/2020-03

[...]

[INFO] --- maven-source-plugin:2.1.1:jar (attach-sources) @ sadlserver-impl ---
[INFO] Building jar: /Users/akos.kitta/Desktop/xxx/sadl-tmp/sadl/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.server/com.ge.research.sadl.server.server-impl/target/sadlserver-impl-3.4.1-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] com.ge.research.sadl.parent ........................ SUCCESS [  0.256 s]
[INFO] com.ge.research.sadl.xtextgenerator ................ SUCCESS [ 10.238 s]
[INFO] Reasoner/Translator ................................ SUCCESS [  0.000 s]
[INFO] Reasoner/Translator API ............................ SUCCESS [  4.521 s]
[INFO] Reasoner/Translator Implementation ................. SUCCESS [  1.277 s]
[INFO] com.ge.research.jena ............................... SUCCESS [  1.121 s]
[INFO] com.ge.research.sadl.errorgenerator ................ SUCCESS [  0.150 s]
[INFO] com.ge.research.sadl ............................... SUCCESS [ 39.598 s]
[INFO] com.ge.research.sadl.jena .......................... SUCCESS [  1.969 s]
[INFO] Jena Reasoner/Translator Plugin for SADL ........... SUCCESS [  1.580 s]
[INFO] com.ge.research.sadl.ide ........................... SUCCESS [  9.117 s]
[INFO] com.ge.research.sadl.ui ............................ SUCCESS [  4.494 s]
[INFO] com.ge.research.sadl.externalmodels ................ SUCCESS [  0.984 s]
[INFO] com.ge.research.sadl.target ........................ SUCCESS [  0.003 s]
[INFO] com.ge.research.sadl.tests ......................... SUCCESS [ 32.145 s]
[INFO] com.ge.research.sadl.ui.tests ...................... SUCCESS [ 43.472 s]
[INFO] SWI-Prolog Reasoner/Translator Plugin for SADL ..... SUCCESS [  0.507 s]
[INFO] com.ge.research.sadl.importer ...................... SUCCESS [ 15.336 s]
[INFO] com.ge.research.sadl.importer.ide .................. SUCCESS [  1.045 s]
[INFO] com.ge.research.sadl.importer.tests ................ SUCCESS [  3.166 s]
[INFO] com.ge.research.sadl.importer.ui ................... SUCCESS [  1.339 s]
[INFO] com.ge.research.sadl.importer.ui.tests ............. SUCCESS [ 11.730 s]
[INFO] SADL Test Suite .................................... SUCCESS [  5.843 s]
[INFO] com.ge.research.sadl.testsuite.ide ................. SUCCESS [  0.660 s]
[INFO] com.ge.research.sadl.testsuite.tests ............... SUCCESS [  3.337 s]
[INFO] com.ge.research.sadl.testsuite.ui .................. SUCCESS [  1.319 s]
[INFO] com.ge.research.sadl.testsuite.ui.tests ............ SUCCESS [ 10.399 s]
[INFO] com.ge.research.sadl.applications .................. SUCCESS [  0.368 s]
[INFO] com.ge.research.sadl.perspective ................... SUCCESS [  0.399 s]
[INFO] SADL 3 ............................................. SUCCESS [  0.155 s]
[INFO] SADL 3 Update Site ................................. SUCCESS [  3.426 s]
[INFO] SADL Knowledge Services ............................ SUCCESS [  0.000 s]
[INFO] SadlServer API ..................................... SUCCESS [  0.485 s]
[INFO] SadlServer Implementation .......................... SUCCESS [  3.911 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:00 min
[INFO] Finished at: 2020-10-19T11:28:54+02:00
[INFO] Final Memory: 297M/1004M
[INFO] ------------------------------------------------------------------------
akos.kitta@Akoss-MacBook-Pro com.ge.research.sadl.parent % 
```

**Comment by crapo** [comment] 2020-10-19 13:30
@kittaakos , the failure was caused by the added call to projectHelper.getReferencedProjectURIs from a JUnit test case. Since there is no .project file in the project (.../c.om.ge.research.sadl.tests\test-data\test-project\.project) an exception is thrown that I wasn't catching. This isn't a synthetic Resource URI. Just catch and ignore FileNotFoundException from SadlIdeProjectHelpfer.getReferencedProjectURIs?

**Comment by crapo** [comment] 2020-10-20 17:42
I think this is now working although there aren't any JUnit tests and I'm not sure how to create such...

**Closed as completed by crapo** 2020-10-20 17:42 UTC

**Comment by kittaakos** [comment] 2020-10-20 17:55
> there aren't any JUnit tests

We [have JUnit Plug-in tests](https://github.com/SemanticApplicationDesignLanguage/sadl/pull/531/commits/bddf242608ed98462defa1281d9a7b0650b9dd40#diff-84ea7a7c747650a895a836f76a8ed83128810e0ec424c3eecc791cdc564f4e6c). In headless mode, projects cannot be handled as-is. If we want to have headless tests with project support, we have to implement it through the LS.
